### ISSUE TITLE
Errors in non-sandbox envs

### ISSUE THREAD

**Issue by jbuck94** [usevenice/venice#10]
I am looking to use the plaid `development` environment, and have set the secrets via the env var `int_plaid__secrets__development` in vercel.  When I click "New Connection" in the browser, I get the following logged to the JS console

```
[useVeniceConnect] int_plaid Connection failed TRPCClientError: Unable to get client envName=sandbox
```

And the HTTP request to `/api/preConnect` has a payload of:

```JSON
{
  "0": [
    {
      "id": "int_plaid"
    },
    {
      "envName": "sandbox"
    }
  ]
}
```
and response of:

```JSON
[{"id":null,"error":{"message":"Unable to get client envName=sandbox","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"preConnect"}}}]
```

It seems the system is not picking up the `development` env

**Comment by jbuck94** [comment]
Wondering if this relates to `Implement developer mode tooling` Todo on the board here: https://github.com/orgs/usevenice/projects/1/views/1

**Comment by tonyxiao** [comment]
Try adding `&env=development` to the end of your url. Neglected to add docs for this, will do now.

**Comment by tonyxiao** [comment]
Readme updated. Please reopen if issue is not resolved

**Comment by jbuck94** [comment]
Namely, the plaid logs show the transactions webhook is throwing a 500 error.  Im happy to provide log IDs or more details if that will help

**Comment by tonyxiao** [comment]
For env var, not at the moment. The intention is that you should be able to dynamically choose which env you connect to. However, I'll think about whether it makes sense to use env var to set a "default environment"

Can you try to trigger a manual sync from the UI and see if it's successful? Yea please open an issue for the 500 error and I'd be happy to investigate.

**Comment by iwasrobbed** [comment]
@jbuck94 Hey 👋  Just a heads up, we launch a hosted version of Venice yesterday that makes getting your financial data super easy. Try it out here: https://app.venice.is
