### ISSUE TITLE
[Banking] Additional Transaction Sources 

### ISSUE THREAD

**Issue by latetedemelon** [useVenice/venice#41]
Is there a plan or timeline to encorporate any integrations with other bank transaction providers?

- [ ] Yodlee
- [x] Plaid
- [ ] Finicity
- [ ] Tink
- [ ] Nordigen
- [ ] Belvo
- [ ] MX / Simplefin
- [ ] Stripe Financial Connections

**Comment by iwasrobbed** [comment]
Hi @latetedemelon 👋 

We currently have Plaid built-in already as our primary bank data provider (and are in partnership discussions so we can't really speak to that too much). As Plaid gives us a lot of coverage across US & Canada already, we're focusing in on additional financial data areas next across accounting (see https://app.venice.is/integrations). You can also see our near-term [roadmap here](https://github.com/orgs/useVenice/projects/1/views/1).

So we can best understand your needs: Can you help us understand the use case for all the other providers you've listed here? Is it just to give you an international footprint while building an app for others or are you building something internally for yourself?

Thanks!

**Comment by latetedemelon** [comment]
Hi @iwasrobbed 

My comment was related to bank coverage.  Plaid doesn't have full coverage for US / Canada. and I know competetors have 2 to get full coverage (Plaid + Fincity for example).  Nordigen has European coverage  (https://nordigen.com/en/coverage/) etc.

Personally I was actually looking at creating something like what you have (more of a self hosting model though) that included manual transactions via CSV, QIF, OFX, QFX or MT940 etc.  However if you're planning on doing it already I can consider the need filled :)

**Comment by iwasrobbed** [comment]
Thanks for the extra information @latetedemelon!

Although not on Venice's immediate roadmap, we happily accept pull requests for financial data ingestion like the manual transactions you listed (pretty much as long as it's financial data useful to companies, we're open to supporting it)

The goal of Venice is really to enable the long tail of integrations to be built and collectively maintained by the open source community as a whole. So even if it's not one we're using immediately, if it's useful enough for one person in the community to build and maintain, we'd love the help building & maintaining it 😄

Just trying to prevent people from recreating the same wheel everyone does on the infrastructure / data streaming side of things. We're ultimately an orchestration platform that pieces together integrations under a common data streaming protocol. We have a hosting option but can be self-hosted too if desired.

See some [integration examples here](https://github.com/useVenice/venice/tree/main/integrations) (many of these need updates / are partially built as they were just for early data model & architecture development)

**Comment by iwasrobbed** [comment]
@latetedemelon Hey Rob - Just a note I've captured all of these (and many more) in our roadmap. We'll be creating tickets for each so I'll be closing out this ticket for now

https://github.com/orgs/useVenice/projects/1/views/1

Thanks again and let us know if you'd like to work together on building an integration! Happy to jump on a call any time too
