### ISSUE TITLE
Transaction Enrichment Data

### ISSUE THREAD

**Issue by latetedemelon** [useVenice/venice#42]
Are there any roadmap items for transaction enrichment?  I'm thinking of something like from ntropy.com or importing Amazon / Paypal info and combining with transaction data.

**Comment by iwasrobbed** [comment]
Hey @latetedemelon 👋  

For sure, this is an area of interest for us & we're exploring a few different partnerships. At this time, we don't have any intention of building enrichment ourselves as we feel there are already some great options available. 

Our goal is really just to make it easy to use them and connect directly into your Venice data so it's automatically enriched sort of as a plug-in layer.

If you have specific enrichment use cases in mind (for yourself or end users), let us know and happy to work with you on this!

(Feel free to schedule a call as well if easier: https://calendly.com/rob-venice/30-mins)

**Comment by iwasrobbed** [comment]
Added these to our roadmap (feel free to suggest any others I may have missed) and will open new tickets for those so going to close this one out

Thanks again @latetedemelon !

https://github.com/orgs/useVenice/projects/1/views/1
