### ISSUE TITLE
Integrated with VTable

### ISSUE THREAD

**Issue by fangsmile** [useVenice/venice#57]
Whether it can be integrated with VTable. VTable table library has a strong visual display ability and high-performance.
You can check the VTable website for more information：https://visactor.io/vtable
Github: https://github.com/VisActor/VTable
![img_v3_029n_c20f8bf0-914d-480e-9369-9541ff50bc7g](https://github.com/useVenice/venice/assets/3468473/15962663-bcfd-48ea-8612-8134b8178053)

**Comment by tonyxiao** [comment]
looks great but it's out of scope for this project as it's dealing with the data intrgration aspect only.
