### ISSUE TITLE
400 error during preConnect after initial deploy

### ISSUE THREAD

**Issue by iwasrobbed** [usevenice/venice#8]
Hi all 👋 

I tried out Venice this morning—love the idea—but hit a snag when trying to add a new connection:

```
[{"id":null,"error":{"message":"invalid_type at mutations.preConnect.input.config: Required","code":-32600,"data":{"code":"BAD_REQUEST","httpStatus":400,"path":"preConnect"}}}]%
```

The cURL equivalent is:
```bash
curl 'https://api-iu289via0-fastlane-happiness.vercel.app/api/preConnect?batch=1' \
  -H 'authority: api-iu289via0-fastlane-happiness.vercel.app' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer [redacted]' \
  -H 'content-type: application/json' \
  -H 'origin: https://api-fastlane-happiness.vercel.app' \
  -H 'referer: https://api-fastlane-happiness.vercel.app/' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  -H 'x-ledger-id: iwasrobbed' \
  --data-raw '{"0":[{"id":"int_plaid"},{"envName":"sandbox"}]}' \
  --compressed
```

Any ideas what the issue could be?

<img width="616" alt="Screen Shot 2022-10-07 at 1 29 02 PM" src="https://user-images.githubusercontent.com/317671/194615872-1e178738-446c-4185-85fc-338d54f6aafe.png">

**Comment by tonyxiao** [comment]
Hi @iwasrobbed , did you add environment variables for Plaid? It looks like the plaid provider is missing the `config` needed to work.

**Comment by iwasrobbed** [comment]
Hey @tonyxiao - I believe so, using the sandbox (followed the [video](https://www.loom.com/share/a2eda4cd5c764963bd2d6a56fe5a71e5)). I double-checked all the keys match the same fields you used in the video just in case

I'll try and run a local instance to see what's going on

<img width="930" alt="Screen Shot 2022-10-08 at 11 11 07 PM" src="https://user-images.githubusercontent.com/317671/194736001-04022be0-385a-400e-afc8-efa52f50de2b.png">

**Comment by tonyxiao** [comment]
That's strange, I will try to repro this today. The codebase has evolved since I did the video so there might have been an installation regression.

**Comment by tonyxiao** [comment]
Both issues should be resolved

# 400 error
![CleanShot 2022-10-10 at 06 00 05@2x](https://user-images.githubusercontent.com/696842/194797603-30f0b029-7903-43f0-9fe5-0b56415a63eb.png)

This was due to a bad dependency upgrade. Fixed here and added a test for future https://github.com/usevenice/venice/commit/af4ab64c9af7536172861637f01d70e75c434fce

# ERR_PNPM_PATCH_NOT_APPLIED for local development

Should be fixed here. https://github.com/usevenice/venice/commit/41dee9390e813d18d2c30461a6774fcfa26a61df

Let me know if it looks good on your end.

**Comment by iwasrobbed** [comment]
Thanks @tonyxiao, that got me past the issues enumerated above

Seeing other issues now once a connection is actually added (e.g. using Plaid's `Platypus` examples)

<img width="1788" alt="Screen Shot 2022-10-10 at 3 24 27 PM" src="https://user-images.githubusercontent.com/317671/194938741-f39e08eb-c6d7-4af2-ab24-f3c8de36c91d.png">

The calls seem to continuously hit / poll the server w/ 500s. Happy to open a new issue if you'd prefer or provide any extra details as needed

**Comment by tonyxiao** [comment]
Hmm, might be an issue with sandbox data. This is the line that validates it. https://github.com/usevenice/venice/blob/main/packages/cdk-core/meta.types.ts#L26

Can you let me know what is the value of the `loginUrl` from your database?

And yes separate issue would be better :) Thank you.
